integration/test_virt: Assert 'profiles' type
When get_profiles() fails, it returns a string with an error message.
This causes the integration tests to fail as follows:

-> integration.modules.test_virt.VirtTest.test_default_esxi_profile
	Traceback (most recent call last):
	File "/salt/tests/integration/modules/test_virt.py", line 38, in test_default_esxi_profile
		nicp = profiles["nic"]["default"]
	TypeError: string indices must be integers

By asserting the return type of get_profiles(), the error message would
indicate the actual reason for the failure:

-> integration.modules.test_virt.VirtTest.test_default_esxi_profile
	Traceback (most recent call last):
	File "/salt/tests/integration/modules/test_virt.py", line 39, in test_default_esxi_profile
		self.assertIsInstance(profiles, dict)
	AssertionError: 'ERROR: Sorry, localhost failed to open a connection to the hypervisor software at None' is not an instance of <class 'dict'>

Signed-off-by: Radostin Stoyanov <rstoyanov@fedoraproject.org>